image: "rust:latest"

before_script:
  - rustup component add rustfmt
  - rustup default nightly
  - rustup component add rustfmt
  - cargo install cargo-make

stages:
  # - build
  - verify
  # - coverage

# build:
#   stage: build
#   script:
#     - cargo make build

verify:
  stage: verify
  script:
    - apt update
    - apt install firefox-esr -y
    - cargo make verify
# coverage:
#   stage: coverage
#   script:
#     - cargo make coverage
