image: "rust:latest"

before_script:
  - cargo install cargo-make

stages:
  - verify
  # - coverage

verify:
  stage: verify
  script:
    - apt update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install ./google-chrome-stable_current_amd64.deb -y
    - rustup component add rustfmt clippy
    - cargo make verify
# coverage:
#   stage: coverage
#   script:
#     - cargo make coverage
