image: "rust:latest"

before_script:
  - rustup default nightly
  - cargo install cargo-make

stages:
  - build
  - verify
  - coverage

build:
  stage: build
  script:
    - cargo make build

verify:
  stage: verify
  script:
    - cargo make verify

coverage:
  stage: coverage
  script:
    - cargo make coverage
