[config]
skip_core_tasks = true

[tasks.run_watch]
workspace = false
run_task = [
    { name = "run" },
]
watch = true

[tasks.build_watch]
workspace = false
description = "Watch files and recompile the project on change"
run_task = [
    { name = "build" },
]
watch = true

[tasks.check_watch]
workspace = false
description = "Watch files and check the project on change"
run_task = [
    { name = "check" },
]
watch = true

[tasks.doc_open]
workspace = false
command = "cargo"
args = ["doc", "--open", "--document-private-items"]

[tasks.doc]
workspace = false
command = "cargo"
args = ["doc", "--document-private-items"]

[tasks.doc_watch]
workspace = false
run_task = [
    { name = "doc" },
]
watch = true

[tasks.coverage]
workspace = false
install_crate = "cargo-tarpaulin"
command = "cargo"
args = ["tarpaulin", "--all", "--out", "Html", "--output-dir", "target"]


[tasks.coverage_open]
workspace = false
dependencies = ["coverage"]
command = "firefox"
args = ["target/tarpaulin-report.html"]

[tasks.report]
workspace = false
command = "pdflatex"
args = ["-halt-on-error", "-output-directory", "report", "report/report.tex"]


[tasks.report_watch]
workspace = false
run_task = [
    { name = "report" },
]
watch = true
