[config]
skip_core_tasks = true

[tasks.build_watch]
workspace = false
description = "Watch files and recompile the project on change"
run_task = [
    { name = "build" },
]
watch = true

[tasks.check_watch]
workspace = false
description = "Watch files and check the project on change"
run_task = [
    { name = "check" },
]
watch = true

[tasks.doc_open]
workspace = false
command = "cargo"
args = ["doc", "--open", "--document-private-items"]

[tasks.doc]
workspace = false
command = "cargo"
args = ["doc", "--document-private-items"]

[tasks.doc_watch]
workspace = false
run_task = [
    { name = "doc" },
]
watch = true